apiVersion: v1

kind: ConfigMap

metadata:
  name: aws-auth
  namespace: kube-system

data:
  mapRoles: |
    #- rolearn:  arn:aws:iam::AccountId:role/devel-worker-nodes-NodeInstanceRole-14W1I3VCZQHU7
    - rolearn:  arn:aws:iam::047786125310:role/kubernetes_deployment
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::047786125310:role/codebuild-role
      username: build
      groups:
        - system:masters